Markdown fixes
chanzuckerberg/cloud-blobstore pull request #30
Opened 2019-09-03 19:14 UTC by chmreid

This PR modifies markdown files in the repository. It cleans up markdown formatting issues, and clarifies the instructions in the readme.

2019-09-16 19:53 UTC, DailyDreaming approved these changes

2019-09-16 19:57 UTC, DailyDreaming requested changes
```
- All Pull Request relating to an issue must include "connected to 
  #123", where #123 is the issue number.
```

Seems to have been replaced with:

```
1. All pull requests relating to an issue must include the text
   "fixes \#123" or "closes \#123", where \#123 is the issue number.
```

Please swap back, as we don't want github keywords auto-closing issues in order to keep zenhub consistent.

2019-09-17 01:56 UTC, chmreid commented
My bad - I thought that was the point of adding the cross-reference to the issue. I can see now how that could be problematic.

2019-09-17 02:02 UTC, chmreid commented
Here is the updated version:

> 1. All pull requests relating to an issue must include the text
>   "connected to \#123", where \#123 is the issue number. (Using
>   the keywords "closes \#123" or "fixes \#123" will automatically
>   close issue \#123 when the pull request is merged.)

I've mentioned all three keywords, since only mentioning "connected" makes it seem like the author meant "closes" or "fixes" (which is why I changed it in the first place).

2019-09-29 03:25 UTC, DailyDreaming approved these changes

2019-09-30 22:38 UTC, merged